name: 'silver_screen'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# In dbt, the default materialization for a model is a view. This means, when we run 
# dbt run or dbt build, all of our models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the models folder to 
# instead be materialized as tables/views. 

models:
 silver_screen: 
    facts:
      +materialized: view
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
